### PR TITLE
Re-throw if caught #115

### LINKED ISSUE #115: Migrations don't throw if caught migration fails.
I left out a re-throw.

### PR DESCRIPTION
**Pull request by kenrestivo-stem**
Fixes #115

### CODE REVIEW

**Comment by yogthos** [comment]
👍

**Comment by kenrestivo-stem** [comment]
Can you bump revision and deploy to clojars?

**Comment by yogthos** [comment]
sure thing

**Comment by yogthos** [comment]
should be up

**Comment by kenrestivo-stem** [comment]
thanks!

**Pull request merged**
