### PR TITLE
deps cli and timbre

### PR DESCRIPTION
**Pull request by dpom**
- add deps cli as an alternative to leiningen for development
- uses timbre for logging

### CODE REVIEW

**Comment by yogthos** [comment]
I'm ok with adding support for CLI, although I'd prefer to use Babashka to shell scripts there. I disagree with using timbre because I think that's too opinionated. The library should not default to a particular logger implementation and clojure.tools.logging is an API where the logger used in the application can be plugged in.

**Comment by dpom** [comment]
I understand your reluctance, each developer creates their own toolkit according to their experiences and inclinations. Although I worked for years with leiningen I always found it a bit too rigid, I tried boot but I found it too complicated, but as soon as deps cli and tools.build appeared I adopted them because I think they are the optimal solution for balance between ease of use and extensibility.
I worked with XML for many years (I had even become a specialist in XSLT) so I somehow developed an aversion to XML configuration files and that's why I use timbre.
The (selfish) reason I put this PR is to simplify the work of updating my fork with the new versions of migratus :)

**Comment by yogthos** [comment]
So, good news is that I did end up merging [this pr](https://github.com/yogthos/migratus/pull/212) for deps support. I'm starting to use tools.deps and tools.build myself nowadays, but simply haven't had time or any real need to update existing libraries.

**Comment by dpom** [comment]
> So, good news is that I did end up merging [this pr](https://github.com/yogthos/migratus/pull/212) for deps support. I'm starting to use tools.deps and tools.build myself nowadays, but simply haven't had time or any real need to update existing libraries.

Thanks

**Pull request closed without merging**
