### PR TITLE
Add thread cancellation point and return information from migrate-up*

### PR DESCRIPTION
**Pull request by jonathannewman**
When many migrations are being applied, and the underlying database
is slow, the migrations can take a long time.  If the thread running
the migrations is cancelled, it may not be interrupted until all the
migrations are complete.

To allow the thread to terminate earlier, this injects a
thread cancellation check into the `migrate-up*` function.

To allow callers to be able to detect partial migrations, the
result code for `:ignore` and `:failure` are also returned. Successful
migrations return nil.

### CODE REVIEW

**Comment by yogthos** [comment]
Thanks, just pushed out `1.0.8` with the update.

**Comment by yogthos** [comment]
Could you also update the readme to document the feature.

**Comment by jonathannewman** [comment]
Thanks!  I'll put together a PR to update the README and CHANGES file.

**Comment by yogthos** [comment]
👍

**Pull request merged**
