### PR TITLE
Adding support for db reset.

### PR DESCRIPTION
**Pull request by gumpt**
Rails has a "db:reset" concept which I find helpful when rapid prototyping -- I want to throw everything away and start fresh.

### CODE REVIEW

**Comment by gumpt** [comment]
I realize I could have bumped the version number. >.<

**Comment by yogthos** [comment]
thanks

**Comment by yogthos** [comment]
just pushed the new version to clojars

**Comment by gumpt** [comment]
Wow, that was quick!  Thanks!

Mind taking a look at the [equivalent PR](https://github.com/yogthos/migratus-lein/pull/11) for migratus-lein?

**Pull request merged**
